### ISSUE TITLE
Sub tabs for images and videos

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#294] opened 2017-03-20 19:59 UTC
Suppose you want to have tweets with images we can search for `Search query /image`.
For example, if we want to search for tweets with images for search query 'barca' , we can instead search for 'barca /image'.

For search query with only images
![screen shot 2017-03-21 at 1 28 13 am](https://cloud.githubusercontent.com/assets/15813932/24118986/b62e9320-0dd5-11e7-9b94-93e88b0911b7.png)

For search query 
![screen shot 2017-03-21 at 1 28 03 am](https://cloud.githubusercontent.com/assets/15813932/24118995/c030cec4-0dd5-11e7-85ab-bd0eb1c832d9.png)

Same goes for videos. Example 'barca /video' . 
This will make our work easy. :)
My idea is that we should go through the loklak_server once and find out what patterns we can apply in search query so as to implement Image , video and other new sub tabs.

**Comment by hemantjadon** [comment] 2017-03-20 20:07
@Achint08 refer to https://github.com/fossasia/loklak_search/issues/3#issuecomment-254788901
Coz I was stuck here. before implementing the image search we need to fetch the images and display them. I guess this is duplicate of #3, but as it is still unresolved I don't know how to proceed.

**Comment by Achint08** [comment] 2017-03-20 20:22
@hemantjadon We can implement video thing even now.
Rest about images, it needs to be resolved from server side only. This will be resolved soon. I am creating an issue there. :)

**Comment by hemantjadon** [comment] 2017-07-12 11:00
Implemented thus can be closed

**Closed by hemantjadon** 2017-07-12 11:00 UTC
