### ISSUE TITLE
Clicking outside the Menu in Header should close it

### ISSUE THREAD

**Issue by jajodiaraghav** [fossasia/loklak_search#638] opened 2018-01-16 18:03 UTC
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Right now to close the Menu, one needs to click on the link again.

**Expected behavior:**
Clicking anywhere outside it, should close it.

**Comment by jajodiaraghav** [comment] 2018-01-16 18:03
Claiming this issue

**Comment by singhpratyush** [comment] 2018-01-16 18:06
Is this duplicate of https://github.com/fossasia/loklak_search/issues/632?

**Comment by ParthS007** [comment] 2018-01-16 18:10
yes @singhpratyush , It is a duplicate of #632

**Comment by jajodiaraghav** [comment] 2018-01-16 18:10
@singhpratyush Yes, you are right. I didn't see it.
The title "9-dot navigation menu to other apps not closing" sounds dubious to me

**Comment by jajodiaraghav** [comment] 2018-01-22 11:05
No update has been made on #632 for the past 18 days.
@singhpratyush @ParthS007 Can I claim this?

**Comment by simsausaurabh** [comment] 2018-02-12 05:38
@singhpratyush this issue can be closed, since it's already been solved.

**Closed** 2018-02-12 08:04 UTC
