### ISSUE TITLE
Typing on front page results in missing the first letter

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#580] opened 2017-10-21 01:47 UTC
Typing a search term on the front page results in a missing first letter. Expected: The full search term should appear in the search bar.

**Comment by VibhorCodecianGupta** [comment] 2017-12-10 17:51
Hello, could you please send in a live link or a GIF reproducing the bug? I don't seem to be able to do that, it is working fine on my machine

**Comment by Achint08** [comment] 2017-12-11 10:41
@VibhorCodecianGupta Reproduce this bug on Mozzila Firefox. While entering a search term on the home page, it will redirect you to the search page where the first letter will be missing out while redirecting.

**Comment by ParthS007** [comment] 2017-12-14 21:46
@mariobehling Please close this issue as it is already resolved.Thanks 👍

**Comment by praveenojha33** [comment] 2018-01-29 16:39
@ParthS007 I have faced this issue today on Google Chrome.It can be reproduced by opening the loklak.org on chrome and entering any search term.It will be redirected to the search page where the first letter will be missing.

**Comment by mariobehling** [comment] 2018-03-02 01:08
@ParthS007 It is still not resolved.

**Comment by Orbiter** [comment] 2018-03-02 06:50
I believe this is related (possibly caused by) to https://github.com/fossasia/loklak_search/issues/663

**Comment by Remorax** [comment] 2018-03-15 17:54
I would like to work on this issue.

**Comment by singhpratyush** [comment] 2018-03-18 10:32
Fixed in c2a49516bcee6e86c56b140d51ce9876a5fcdd92.

**Closed by singhpratyush** 2018-03-18 10:32 UTC
Labels: Hacktoberfest, Priority: HIGH, bug
