### ISSUE TITLE
404 Image Error in Media Wall

### ISSUE THREAD

**Issue by Remorax** [fossasia/loklak_search#688] opened 2018-03-18 00:00 UTC
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
On going to the Media wall, switching the image filter to True and searching for a word, sometimes we receive a 404 error in place of the original image.

**Expected behavior:**
It should return the original image instead.

**Screenshots of the issue:**
![screen shot 2018-03-18 at 5 15 03 am](https://user-images.githubusercontent.com/26062692/37561108-0fc19046-2a6c-11e8-83b8-37cb4afdc020.png)

I would like to work on this 😄

**Comment by simsausaurabh** [comment] 2018-03-18 08:39
@Remorax It seems this issue is a duplicate of #653.

**Comment by Remorax** [comment] 2018-03-18 10:14
Oh, okay. Can you close that issue as I've already resolved this issue through #689 ?

**Closed** 2018-03-22 09:12 UTC
