### ISSUE TITLE
Hashtag on start page not displaying top hashtags of previous hours

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#864] opened 2018-07-19 14:02 UTC
The hashtags on the start page are not displaying the actual top hashtags. Expected is, that the top hashtags of the last few hours are displayed. However every few minutes completely different hashtags are displayed.

**Comment by simsausaurabh** [comment] 2018-08-15 11:01
The issue has been fixed in #896. The hashtags are actually not changing now, they are getting replaced in the Ngrx store by feed result hashtags, and on going to main page of loklak, they get back to their original state. The issue is to stop it from getting replaced by result feed hashtags. Its more relevant issue has been opened here: #910. Closing this issue :+1:.

**Closed** 2018-08-15 11:01 UTC
Labels: bug
