### ISSUE TITLE
Incorrect Tweet text displayed

### ISSUE THREAD

**Issue by singhpratyush** [fossasia/loklak_search#426] opened 2017-06-25 20:30 UTC
The query `from:singhpratyush_` shows a Tweet which looks like this - 

![screenshot from 2017-06-26 01 49 06](https://user-images.githubusercontent.com/10860278/27519457-ee398986-5a11-11e7-8a3a-6467920516fb.png)

While the response from loklak search is something like this -

![screenshot from 2017-06-26 01 51 25](https://user-images.githubusercontent.com/10860278/27519470-2c120620-5a12-11e7-97ce-7c64e9be0f99.png)

This is how it looks [on Twitter](https://twitter.com/singhpratyush_/status/877723071498649600) - 
![screenshot from 2017-06-26 01 53 43](https://user-images.githubusercontent.com/10860278/27519518-28ea2f94-5a13-11e7-8a9c-df561a84fa78.png)

**Comment by hemantjadon** [comment] 2017-06-27 03:23
@singhpratyush on my device (OSX, Chrome59) I am able to see the Flag, but the text Germany is showing twice I wonder why it is so.

**Comment by singhpratyush** [comment] 2017-06-27 04:37
@hemantjadon: Can you please share the screenshot from loklak search?

**Comment by hemantjadon** [comment] 2017-06-27 13:21
@singhpratyush The screenshot  (Chrome59, macOS-Sierra)
![screen shot 2017-06-27 at 6 49 17 pm](https://user-images.githubusercontent.com/11755543/27589568-84d536e4-5b69-11e7-95b6-2c927b1c581a.png)

**Comment by simsausaurabh** [comment] 2018-06-22 19:42
@singhpratyush Does this issue still persist? Can we reproduce it?

**Comment by simsausaurabh** [comment] 2018-07-28 15:52
Duplicate of #673. This can be closed.

**Closed** 2018-07-28 17:08 UTC
Labels: bug, needs more information
