### ISSUE TITLE
Suggestions staying even when search result is already being displayed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#439] opened 2017-07-06 01:42 UTC
Please only show suggestions during typing. Compare it to Google, please.
![screenshot from 2017-07-06 03-40-23](https://user-images.githubusercontent.com/1583873/27891955-321e0936-61fd-11e7-9366-8f78b951aa41.png)

**Comment by mariobehling** [comment] 2017-07-18 14:29
Still not solved.

**Comment by singhpratyush** [comment] 2017-07-18 14:35
@mariobehling: It seems fixed for me. Have you tried a hard refresh (`CTRL+F5`).

**Comment by hemantjadon** [comment] 2017-07-18 14:42
@mariobehling I fixed this in above PR, can you please check again

**Comment by simsausaurabh** [comment] 2018-07-28 15:58
Duplicate of #549 and seems to be fixed now.

**Closed** 2018-07-28 17:09 UTC
Labels: bug
