### ISSUE TITLE
No results take a long time

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#334] opened 2017-04-29 13:49 UTC
Trying a search that does not have any result takes a long time, while on loklak.org the result is immediate.

![screenshot from 2017-04-29 15-13-26](https://cloud.githubusercontent.com/assets/1583873/25555951/71e2d27a-2cf3-11e7-8934-271f1339ab22.png)

**Comment by shaz13** [comment] 2017-05-07 14:44
Hi @mariobehling,
Would like to work on this issue. Instead of passing empty result. I think we must block such behavior before the search function starts. or perhaps enable search only after `char > 0 `

**Comment by mariobehling** [comment] 2017-05-07 14:48
Not sure, what is your proposal, but if you have a PR, it would be interesting.

**Comment by hemantjadon** [comment] 2017-06-02 19:52
Not Sure, our application is responding in time, I am not sure what's the reason. I tried many searches random keywords.
Sometimes, the search is slow on API sometimes it is fast on Application.
Actually what  I am able to understand here is that the API responds not in a constant time even for the same query. Maybe due to server load and other traffic related issues, this makes that variable time for each request.

**Comment by hemantjadon** [comment] 2017-08-01 04:48
Closing this for now, Please reopen if this is still an issue. Please do mention the browsers in which the issue is occurring. I have snapshotted the network timeline on chrome and the `No Results` page is shown immediately. Without delay, as soon an empty result is sent by server.

**Closed by hemantjadon** 2017-08-01 04:48 UTC
Labels: bug
