### ISSUE TITLE
Typing a word causes first letter to shift to the end.

### ISSUE THREAD

**Issue by sayak119** [fossasia/loklak_search#627] opened 2017-12-17 22:49 UTC
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
typing a word causes first letter to be at the end of the sentence.

**Expected behavior:**
Should remain the original typed word

**Screenshots of the issue:**

**GIF**

I tried to search for dog here. But the search result it showed was ogd.

![screencast_monday-18-december-2017_04_13_37-ist](https://user-images.githubusercontent.com/28414920/34084678-9fafedaa-e3aa-11e7-8755-0d76de4c1178.gif)

**Comment by bhaveshAn** [comment] 2017-12-19 17:38
I can't able to reproduce this issue

**Comment by apargarg** [comment] 2018-01-02 02:08
Should I take this up or is it solved?

**Comment by singhpratyush** [comment] 2018-01-04 17:10
I am unable to reproduce this error. @sayak119: Please close this issue if you are no longer facing this issue.

**Comment by sayak119** [comment] 2018-01-05 21:58
I got this issue on a slow network.

**Comment by ajayns** [comment] 2018-01-20 04:20
Unable to reproduce this error. Could be a network or browser issue. I've tested on the latest Firefox and Chrome and it has no issues. @sayak119

**Comment by rupav** [comment] 2018-02-03 07:19
this issue can be closed then @sayak119. @singhpratyush please close.

**Comment by singhpratyush** [comment] 2018-02-03 09:41
Closing as this bug hasn't been reproduced.

**Closed by singhpratyush** 2018-02-03 09:41 UTC
