### ISSUE TITLE
Got 500 response while searching, I've attached crash report

### ISSUE THREAD

**Issue by Pankaj-Sakariya** [fossasia/loklak_search#656] opened 2018-02-12 11:20 UTC
**I'm submitting a ...**
- [Got 500 response while searching ] bug report

**Current behavior:**
http://api.loklak.org/x?id=961594308796153857  This is the url. 

**Expected behavior:**

**Screenshots of the issue:**

HTTP ERROR 500
Problem accessing /x. Reason:
```
    Server Error
Caused by:
NoShardAvailableActionException[No shard available for [get [messages_hour][_all][961594308796153857]: routing [null]]]; nested: RemoteTransportException[[Malice][127.0.0.1:9300][indices:data/read/get[s]]]; nested: IndexNotFoundException[no such index];
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:199)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.onFailure(TransportSingleShardAction.java:186)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.access$1300(TransportSingleShardAction.java:115)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleException(TransportSingleShardAction.java:240)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:872)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:850)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:387)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: RemoteTransportException[[Malice][127.0.0.1:9300][indices:data/read/get[s]]]; nested: IndexNotFoundException[no such index];
Caused by: [messages_hour] IndexNotFoundException[no such index]
	at org.elasticsearch.indices.IndicesService.indexServiceSafe(IndicesService.java:310)
	at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:94)
	at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:44)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:282)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:275)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by:
RemoteTransportException[[Malice][127.0.0.1:9300][indices:data/read/get[s]]]; nested: IndexNotFoundException[no such index];
Caused by: [messages_hour] IndexNotFoundException[no such index]
	at org.elasticsearch.indices.IndicesService.indexServiceSafe(IndicesService.java:310)
	at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:94)
	at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:44)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:282)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:275)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by:
[messages_hour] IndexNotFoundException[no such index]
	at org.elasticsearch.indices.IndicesService.indexServiceSafe(IndicesService.java:310)
	at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:94)
	at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:44)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:282)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:275)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by VibhorCodecianGupta** [comment] 2018-02-19 11:24
I was not able to reproduce the issue. 
Try hard reloading/cache clearing/deleting browser history once?

**Comment by simsausaurabh** [comment] 2018-05-30 18:42
@singhpratyush is this valid? I guess its not the right form of query pattern. There is no endpoint corresponding to the parameters set in this query. And also, this issue should be opened on server side. If possible, please close this issue.

**Comment by singhpratyush** [comment] 2018-05-31 05:44
Not valid. Depends on contemporary index state.

**Closed** 2018-05-31 05:44 UTC
