### ISSUE TITLE
Images not loading (Firefox)

### ISSUE THREAD

**Issue by AnshulMalik** [fossasia/loklak_search#569] opened 2017-09-07 06:52 UTC
Firefox Version: 55.0.2 (64-bit) Ubuntu 17.04

![a](https://user-images.githubusercontent.com/7821757/30149900-0c530e30-93c7-11e7-8b3b-71f8a71334bb.png)

None of the images loads when using firefox but works fine in chrome.

**Comment by sounak98** [comment] 2017-09-11 07:45
I would like to work on this.

**Comment by AnshulMalik** [comment] 2017-09-11 08:40
Please go ahead @sounak98

**Comment by sudheesh001** [comment] 2017-09-11 10:24
Can you give more details on any console errors that are showing up on firefox? The issue is not very clear.
Needs
- [ ] Error(s) list/trace
- [ ] Regression of various Firefox versions until where it works.

**Comment by ParthS007** [comment] 2017-12-07 14:10
@AnshulMalik Please close the issue as images are loading now .
![image](https://user-images.githubusercontent.com/24358501/33719354-73859bfc-db86-11e7-8d3b-2d6d40528c09.png)

**Comment by rupav** [comment] 2018-02-03 07:45
@AnshulMalik can I work on it. Problem still persists, I am using windows 10.
can you point me where to start looking (firefox browser console logs are showing black page), I am new to angular.

**Comment by sk9331657** [comment] 2018-03-11 04:20
@mariobehling This problem is still persists because the src for image is not being generated in Firefox .
![bo src](https://user-images.githubusercontent.com/17084322/37249645-91e5b42c-2511-11e8-8e4c-f01a63bb60be.png)

**Closed** 2018-03-13 15:35 UTC
Labels: Hacktoberfest
