### ISSUE TITLE
Some Hashtags in Japanese not rendered correctly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#174] opened 2017-01-07 13:26 UTC
It seems that Japanese hashtags/words are not always correctly rendered. I am not sure, why.

![screenshot from 2017-01-07 14-22-02](https://cloud.githubusercontent.com/assets/1583873/21741966/2571c7b8-d4e5-11e6-88c6-2c69648d2cf7.png)

compare: http://loklak.net/search?query=yacy

Search query for #!?*!!$%!? -- gives the result: http://loklak.net/search?query=%23!%3F*!!%24%25!%3F%20--

**Comment by Achint08** [comment] 2017-01-09 00:57
@mariobehling This is not a bug. Problem was with the actual tweet.
![screen shot 2017-01-09 at 6 23 34 am](https://cloud.githubusercontent.com/assets/15813932/21755138/9c661dc4-d634-11e6-83d4-1373cb2041e2.png)

Let's close it.

**Comment by hemantjadon** [comment] 2017-01-09 03:12
Aah this highlights the problem in code I wrote in autolinker moule. All the things which start with '#' are not hashtags, have to use shards and "hashtags" object from the response from the api response.

I will fix this :)

**Closed** 2017-04-04 13:42 UTC
Labels: bug
