### ISSUE TITLE
Add a tweets frequency widget in sidebars for searches

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#260] opened 2017-02-04 11:24 UTC
Showing the tweet frequency is a useful information. Please add this widget to the sidebar.

![screenshot from 2016-11-03 11 39 30](https://cloud.githubusercontent.com/assets/1583873/19955292/da6bd626-a1ba-11e6-8b7d-8e6b8a0ca564.png)

**Comment by rishiraj824** [comment] 2017-02-04 11:26
I am willing to work on this feature. Please assign me this.

**Comment by uttu357** [comment] 2017-02-10 08:15
Duplicate of #188

**Closed** 2017-02-10 18:02 UTC
Labels: enhancement, feature
