### ISSUE TITLE
Increase space above bottom bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#201] opened 2017-01-11 10:07 UTC
The bottom bar is very close to above areas. Please increase the area above the bottom bar on all pages (including search, about, contact etc..)
![screenshot from 2017-01-11 11-06-08](https://cloud.githubusercontent.com/assets/1583873/21844215/14bfb00e-d7ee-11e6-9e65-38970d66463a.png)

**Comment by uttu357** [comment] 2017-01-11 10:23
Duplicate of #69

**Closed** 2017-01-11 10:49 UTC
Labels: enhancement
